# Generated by Django 4.1.3 on 2022-11-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='آدرس ایمیل')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='شماره همراه')),
                ('fullname', models.CharField(max_length=60, verbose_name='شماره همراه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fullname', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('code', models.SmallIntegerField()),
                ('token', models.CharField(max_length=121)),
                ('expiratione_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'رمز یک بار مصرف',
                'verbose_name_plural': 'رمزهای یک بار مصرف',
            },
        ),
    ]
