# Generated by Django 4.1.3 on 2022-11-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=60, verbose_name='نام کامل'),
        ),
    ]
