# Generated by Django 4.1.3 on 2022-11-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModel_app', '0003_alter_otp_password_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
