# Generated by Django 4.1.2 on 2023-01-25 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(blank=True, help_text='این فیلد به صورت خودکار تکمیل می شود', verbose_name='اسلاگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, unique=True, verbose_name='رنگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'رنگ محصول',
                'verbose_name_plural': 'رنگ محصولات',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5, unique=True, verbose_name='اندازه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'اندازه محصول',
                'verbose_name_plural': 'اندازه محصولات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30, verbose_name='اسم محصول')),
                ('description', models.TextField(verbose_name='توضیجات')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('discount', models.PositiveSmallIntegerField(verbose_name='تخفیف')),
                ('image', models.ImageField(upload_to='Product', verbose_name='تصویر محصول')),
                ('feature_product', models.BooleanField(help_text='در صورت فعال بودن گزینه این محصول در بخش محصولات ویژه نمایش داده می شود', verbose_name='محصول ویژه')),
                ('slug', models.SlugField(blank=True, help_text='این فیلد به صورت خودکار تکمیل می شود', verbose_name='اسلاگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد محصول')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_app.category', verbose_name='دسته بندی')),
                ('color', models.ManyToManyField(related_name='products', to='product_app.color', verbose_name='رنگ محصول')),
                ('size', models.ManyToManyField(related_name='products', to='product_app.size', verbose_name='اندازه محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
