# Generated by Django 4.1.2 on 2023-01-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False, help_text='وضعیت انتشار محصول در سایت', verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature_product',
            field=models.BooleanField(help_text='در صورت فعال بودن گزینه،این محصول در بخش محصولات ویژه نمایش داده می شود', verbose_name='محصول ویژه'),
        ),
    ]
