# Generated by Django 4.1.2 on 2023-01-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'بخش نظرات محصول'},
        ),
    ]
