# Generated by Django 4.1.2 on 2023-02-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='Cateory', verbose_name='تصویر دسته بندی'),
        ),
    ]
