# Generated by Django 4.1.2 on 2023-02-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='Cateory', verbose_name='تصویر دسته بندی'),
        ),
    ]
