# Generated by Django 4.1.2 on 2023-02-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_alter_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
