# Generated by Django 4.1.2 on 2023-02-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0003_contactinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'راه ارتباطی', 'verbose_name_plural': 'راه های ارتباطی'},
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='short_description',
            field=models.TextField(max_length=150, verbose_name='توضیح کوتاه'),
        ),
    ]
