# Generated by Django 4.1.2 on 2023-03-01 17:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0005_sendemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendemail',
            options={'verbose_name': 'ارسال پیام', 'verbose_name_plural': 'ارسال پیام ها'},
        ),
        migrations.AlterField(
            model_name='sendemail',
            name='file',
            field=models.FilePathField(blank=True, null=True, verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='sendemail',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='sendemail',
            name='send_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ارسال'),
        ),
        migrations.AlterField(
            model_name='sendemail',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='sendemail',
            name='submit_status',
            field=models.BooleanField(blank=True, verbose_name='وضعیت ارسال پیام'),
        ),
    ]
