# Generated by Django 4.1.2 on 2023-03-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0008_alter_sendemail_options_alter_sendemail_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendemail',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='پیام'),
        ),
    ]
