# Generated by Django 4.1.2 on 2023-02-05 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_app', '0007_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره همراه')),
                ('city', models.CharField(max_length=30, verbose_name='شهر')),
                ('postal_code', models.PositiveIntegerField(verbose_name='کد پستی')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('is_paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='PruductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5, verbose_name='اندازه محصول')),
                ('color', models.CharField(max_length=10, verbose_name='رنگ')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='تعداد')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='basket_app.userorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product_app.product', verbose_name='محصول')),
            ],
        ),
    ]
