# Generated by Django 4.1.2 on 2023-02-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_alter_comment_options'),
        ('basket_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PruductOrder',
            new_name='ProductOrder',
        ),
        migrations.AlterModelOptions(
            name='productorder',
            options={'verbose_name': 'سفارش محصول', 'verbose_name_plural': 'سفارش محصولات'},
        ),
        migrations.AddField(
            model_name='userorder',
            name='fullname',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='نام کامل'),
        ),
        migrations.AddField(
            model_name='userorder',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه کل'),
        ),
    ]
