# Generated by Django 4.1.2 on 2023-02-18 16:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0003_alter_userorder_fullname_alter_userorder_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(max_length=30, unique=True, verbose_name='شناسه کد تخفیف')),
                ('percent', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد کد')),
                ('valid_from', models.DateTimeField(default=datetime.datetime(2023, 2, 18, 19, 37, 24, 313713), verbose_name='تاریخ شروع اعتبار')),
                ('validity', models.PositiveSmallIntegerField(default=1, help_text='تعداد روزهایی که کد اعتبار دارد', verbose_name='اعتبار کد تخفیف')),
                ('expiration_date', models.DateTimeField(blank=True, help_text='به صورت خودکار فیلد تکمیل و بعد از تاریخ به دست آمده کد منقضی میشود', verbose_name='تاریخ انتقضا')),
                ('status', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کد های تخفیف',
            },
        ),
    ]
