# Generated by Django 4.1.2 on 2023-02-18 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0004_discountcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 19, 39, 45, 731045), verbose_name='تاریخ شروع اعتبار'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='validity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='تعداد روزهایی که کد اعتبار دارد', null=True, verbose_name='اعتبار کد تخفیف'),
        ),
    ]
