# Generated by Django 4.1.2 on 2023-02-18 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0006_alter_discountcode_valid_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 19, 41, 39, 181669), verbose_name='تاریخ شروع اعتبار'),
        ),
    ]
