# Generated by Django 4.1.2 on 2023-02-23 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0008_alter_discountcode_valid_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 20, 5, 28, 346399), verbose_name='تاریخ شروع اعتبار'),
        ),
    ]
