# Generated by Django 4.1.2 on 2023-02-24 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0009_alter_discountcode_valid_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 16, 4, 33, 415821), verbose_name='تاریخ شروع اعتبار'),
        ),
    ]
