# Generated by Django 4.1.2 on 2023-03-03 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0016_alter_discountcode_valid_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 14, 22, 146930), verbose_name='تاریخ شروع اعتبار'),
        ),
    ]
