# Generated by Django 4.1.2 on 2023-03-04 12:24

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basket_app', '0017_alter_discountcode_valid_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='used_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='استفاده شده توسط'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 15, 54, 36, 291267), verbose_name='تاریخ شروع اعتبار'),
        ),
    ]
